spring:
  application:
    name: halfmoon
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.30.133:3306/halfmoon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    solr:
      host: http://47.106.234.164:8983/solr/sob_blog_core
server:
  port: 8078

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: isDelete
